In [13]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns
import statsmodels.api as sm
import scipy.stats as sci
from statsmodels.regression.linear_model import OLS


pd.set_option('float_format', '{:6.5f}'.format)
sns.set(style='ticks')

import warnings
warnings.filterwarnings("ignore")

In [14]:
df=pd.read_csv('ccdefaults.txt',sep='\t')

In [15]:
df.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  PAY_3  PAY_4  \
0   1      20000    2          2         1   24      2      2     -1     -1   
1   2     120000    2          2         2   26     -1      2      0      0   
2   3      90000    2          2         2   34      0      0      0      0   
3   4      50000    2          2         1   37      0      0      0      0   
4   5      50000    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...          0          0          0         0       689         0   
1  ...       3272       3455       3261         0      1000      1000   
2  ...      14331      14948      15549      1518      1500      1000   
3  ...      28314      28959      29547      2000      2019      1200   
4  ...      20940      19146      19131      2000     36681     10000   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  DEFAULT  
0         0         0         0        1  
1      1000         0      2000        1  
2      1000      1000      5000        0  
3      1100      1069      1000        0  
4      9000       689       679        0  

[5 rows x 25 columns]

In [16]:
y = df['DEFAULT']
X = df[['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_1',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6']]

In [17]:
X[['SEX', 'EDUCATION', 'MARRIAGE']] = X[['SEX', 'EDUCATION', 'MARRIAGE']].astype(str)

In [18]:
X = pd.get_dummies(X, drop_first = True)

In [19]:
X.columns

Index(['ID', 'LIMIT_BAL', 'AGE', 'PAY_1', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5',
       'PAY_6', 'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4',
       'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3',
       'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'SEX_2', 'EDUCATION_1',
       'EDUCATION_2', 'EDUCATION_3', 'EDUCATION_4', 'EDUCATION_5',
       'EDUCATION_6', 'MARRIAGE_1', 'MARRIAGE_2', 'MARRIAGE_3'],
      dtype='object')

In [21]:
lst_1 = [1,2,3,9,15,21,22,23,24,25,26,27,28,29,30] 
lst_2 = [1,2,3,4,9,10,15,16,21,22,23,24,25,26,27,28,29,30]

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1, stratify = y)

In [23]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

X_train = pd.DataFrame(scaler.fit_transform(X_train))
X_test = pd.DataFrame(scaler.transform(X_test))

In [15]:
#2

from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='adam', hidden_layer_sizes=(500, 500),  # two layers with 500 neurons in each 
                    alpha = .0001,                                 # to mitigate overffiting 
                    random_state = False,
                   learning_rate_init = 0.01)                      # to make steps a bit smaller to find a better minimum in the loss function

clf.fit(X_train.loc[:,lst_1], y_train)
clf.score(X_test.loc[:,lst_1],y_test)

0.8174747474747475

In [16]:
from sklearn.metrics import confusion_matrix                
confusion_matrix(y_test,clf.predict(X_test.loc[:,lst_1]) )      # confusion matrix

array([[7388,  322],
       [1485,  705]])

In [17]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print('accuracy:', accuracy_score(y_true = y_test, y_pred = clf.predict(X_test.loc[:,lst_1])),'\n'
      'precision:', precision_score(y_true = y_test, y_pred = clf.predict(X_test.loc[:,lst_1])),'\n'
      'recall:',recall_score(y_true = y_test, y_pred = clf.predict(X_test.loc[:,lst_1])),'\n'
      'f1:',f1_score(y_test, clf.predict(X_test.loc[:,lst_1])))

accuracy: 0.8174747474747475 
precision: 0.6864654333008764 
recall: 0.3219178082191781 
f1: 0.4382965495803544


In [18]:
#3
clf = MLPClassifier(solver='adam', hidden_layer_sizes=(500, 500), alpha = .0001, learning_rate_init = 0.01,
                   random_state = False)

clf.fit(X_train.iloc[:,lst_2], y_train)
clf.score(X_test.iloc[:,lst_2],y_test)

0.8086868686868687

In [19]:
confusion_matrix(y_true = y_test, y_pred = clf.predict(X_test.iloc[:,lst_2]))

array([[7206,  504],
       [1390,  800]])

In [20]:
print('accuracy:', accuracy_score(y_true = y_test, y_pred = clf.predict(X_test.loc[:,lst_2])),'\n'
      'precision:', precision_score(y_true = y_test, y_pred = clf.predict(X_test.loc[:,lst_2])),'\n'
      'recall:',recall_score(y_true = y_test, y_pred = clf.predict(X_test.loc[:,lst_2])),'\n'
      'f1:',f1_score(y_test, clf.predict(X_test.loc[:,lst_2])))

accuracy: 0.8086868686868687 
precision: 0.6134969325153374 
recall: 0.365296803652968 
f1: 0.45792787635947335


If we take into consideration just the percentage of all misclassified test observations then the first neural network has better performance. However, we might see that the recall coefficient of the second model is better meaning the defualt prediction is more accurate. In my opinion to have more accurate prediction of defaults is better because banks will lose a bit less. Additionally, f1 score of the second model is slightly better which tells us about better performance. Still, the results are not significantly different but the second model is sligtly better, therefore, we need to include additional features. 

In [21]:
#4
clf = MLPClassifier(solver='adam', hidden_layer_sizes=(500,500), alpha = .0001, learning_rate_init = 0.01,
                   random_state = False)

clf.fit(X_train.iloc[:,1:31], y_train)
clf.score(X_test.iloc[:,1:31],y_test)

0.7963636363636364

In [23]:
confusion_matrix(y_true = y_test, y_pred = clf.predict(X_test.iloc[:,1:31]))

array([[7080,  630],
       [1386,  804]])

In [24]:
print('accuracy:', accuracy_score(y_true = y_test, y_pred = clf.predict(X_test.loc[:,1:31])),'\n'
      'precision:', precision_score(y_true = y_test, y_pred = clf.predict(X_test.loc[:,1:31])),'\n'
      'recall:',recall_score(y_true = y_test, y_pred = clf.predict(X_test.loc[:,1:31])),'\n'
      'f1:',f1_score(y_test, clf.predict(X_test.loc[:,1:31])))

accuracy: 0.7963636363636364 
precision: 0.5606694560669456 
recall: 0.36712328767123287 
f1: 0.44370860927152317


The result is sligtly worse than in the previous model. If we compare each coefficient this model practically lose in each value but not so much. Therefore, there is no increase in the prediction accuracy.

In [25]:
#5
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Dropout
from tensorflow.keras import regularizers

#5_2

model = Sequential()                                                   # i use relu finction in the input and hidden layers
#input                                                         in output is sigmoid because it shows like the probability of a particular class
model.add(Dense(len(lst_1), activation = 'relu', input_dim = X_train.loc[:,lst_1].shape[1])) #input layer with the # of neurons that is equal to
#hidden layers                                                                                 the number of the features
model.add(Dense(500, activation = 'relu', kernel_regularizer=regularizers.l2(0.001)))    #2 hidden layers with 500 neurons and alpha = .001
model.add(Dense(500, activation = 'relu'))
#output
model.add(Dense(1, activation = 'sigmoid'))                                

sgd1 = tf.keras.optimizers.SGD(lr=0.01, decay=1e-7)
model.compile(optimizer= sgd1,
              loss='binary_crossentropy', metrics = ['accuracy'])
model.fit(X_train.loc[:,lst_1], y_train, epochs = 500)        #   # of cycles is 500

Train on 20100 samples
Epoch 1/500
20100/20100 [==============================] - 2s 116us/sample - loss: 0.5673 - accuracy: 0.7788
Epoch 2/500
20100/20100 [==============================] - 2s 98us/sample - loss: 0.5491 - accuracy: 0.7788
Epoch 3/500
20100/20100 [==============================] - 3s 144us/sample - loss: 0.5454 - accuracy: 0.7788
Epoch 4/500
20100/20100 [==============================] - 2s 104us/sample - loss: 0.5414 - accuracy: 0.7788
Epoch 5/500
20100/20100 [==============================] - 2s 113us/sample - loss: 0.5365 - accuracy: 0.7788
Epoch 6/500
20100/20100 [==============================] - 2s 104us/sample - loss: 0.5306 - accuracy: 0.7788
Epoch 7/500
20100/20100 [==============================] - 2s 98us/sample - loss: 0.5230 - accuracy: 0.7788
Epoch 8/500
20100/20100 [==============================] - 2s 92us/sample - loss: 0.5149 - accuracy: 0.7789
Epoch 9/500
20100/20100 [==============================] - 2s 95us/sample - loss: 0.5075 - accuracy: 0.7799


In [26]:
confusion_matrix(y_true = y_test, y_pred = model.predict_classes(X_test.iloc[:,lst_1]))

array([[7342,  368],
       [1438,  752]])

In [27]:
print('accuracy:', accuracy_score(y_true = y_test, y_pred = model.predict_classes(X_test.iloc[:,lst_1])),'\n'
      'precision:', precision_score(y_true = y_test, y_pred = model.predict_classes(X_test.iloc[:,lst_1])),'\n'
      'recall:',recall_score(y_true = y_test, y_pred = model.predict_classes(X_test.iloc[:,lst_1])),'\n'
      'f1:',f1_score(y_test, model.predict_classes(X_test.iloc[:,lst_1])))

accuracy: 0.8175757575757576 
precision: 0.6714285714285714 
recall: 0.34337899543378997 
f1: 0.454380664652568


In [28]:
#5_3

model = Sequential()
#input
model.add(Dense(len(lst_1), activation ='relu', input_dim = X_train.loc[:,lst_2].shape[1]))
#hidden layers
model.add(Dense(500, activation = 'relu', kernel_regularizer=regularizers.l2(0.001)))
model.add(Dense(500, activation = 'relu'))
#output
model.add(Dense(1, activation = 'sigmoid'))

sgd1 = tf.keras.optimizers.SGD(lr=0.01, decay=1e-7)
model.compile(optimizer= sgd1,
              loss='binary_crossentropy', metrics = ['accuracy'])
model.fit(X_train.loc[:,lst_2], y_train, epochs = 500)

Train on 20100 samples
Epoch 1/500
20100/20100 [==============================] - 3s 168us/sample - loss: 0.5751 - accuracy: 0.7765
Epoch 2/500
20100/20100 [==============================] - 3s 146us/sample - loss: 0.5539 - accuracy: 0.7788
Epoch 3/500
20100/20100 [==============================] - 3s 138us/sample - loss: 0.5522 - accuracy: 0.7788
Epoch 4/500
20100/20100 [==============================] - 3s 136us/sample - loss: 0.5502 - accuracy: 0.7788 - loss: 0.5489 - accuracy: 0.77 - ETA
Epoch 5/500
20100/20100 [==============================] - 3s 140us/sample - loss: 0.5480 - accuracy: 0.7788
Epoch 6/500
20100/20100 [==============================] - 3s 134us/sample - loss: 0.5455 - accuracy: 0.7788
Epoch 7/500
20100/20100 [==============================] - 3s 134us/sample - loss: 0.5425 - accuracy: 0.7788
Epoch 8/500
20100/20100 [==============================] - 3s 142us/sample - loss: 0.5387 - accuracy: 0.7788
Epoch 9/500
20100/20100 [==============================] - 3s 137us

In [29]:
confusion_matrix(y_true = y_test, y_pred = model.predict_classes(X_test.iloc[:,lst_2]))

array([[7329,  381],
       [1427,  763]])

In [30]:
print('accuracy:', accuracy_score(y_true = y_test, y_pred = model.predict_classes(X_test.iloc[:,lst_2])),'\n'
      'precision:', precision_score(y_true = y_test, y_pred = model.predict_classes(X_test.iloc[:,lst_2])),'\n'
      'recall:',recall_score(y_true = y_test, y_pred = model.predict_classes(X_test.iloc[:,lst_2])),'\n'
      'f1:',f1_score(y_test, model.predict_classes(X_test.iloc[:,lst_2])))

accuracy: 0.8173737373737374 
precision: 0.666958041958042 
recall: 0.34840182648401824 
f1: 0.45770845830833834


In [31]:
#5_4

model = Sequential()
#input
model.add(Dense(len(lst_1), activation = 'relu', input_dim = X_train.loc[:,1:31].shape[1]))
#hidden layers
model.add(Dense(500, activation = 'relu', kernel_regularizer=regularizers.l2(0.001)))
model.add(Dense(500, activation = 'relu'))
#output
model.add(Dense(1, activation = 'sigmoid'))

sgd1 = tf.keras.optimizers.SGD(lr=0.01, decay=1e-7)
model.compile(optimizer= sgd1,
              loss='binary_crossentropy', metrics = ['accuracy'])
model.fit(X_train.loc[:,1:31], y_train, epochs = 500)

Train on 20100 samples
Epoch 1/500
20100/20100 [==============================] - 3s 162us/sample - loss: 0.5679 - accuracy: 0.7788
Epoch 2/500
20100/20100 [==============================] - 3s 134us/sample - loss: 0.5502 - accuracy: 0.7788
Epoch 3/500
20100/20100 [==============================] - 3s 134us/sample - loss: 0.5464 - accuracy: 0.7788
Epoch 4/500
20100/20100 [==============================] - 3s 133us/sample - loss: 0.5419 - accuracy: 0.7788
Epoch 5/500
20100/20100 [==============================] - 3s 134us/sample - loss: 0.5363 - accuracy: 0.7788
Epoch 6/500
20100/20100 [==============================] - 3s 136us/sample - loss: 0.5297 - accuracy: 0.7788 - loss: 0.529
Epoch 7/500
20100/20100 [==============================] - 3s 154us/sample - loss: 0.5223 - accuracy: 0.7788
Epoch 8/500
20100/20100 [==============================] - 3s 134us/sample - loss: 0.5153 - accuracy: 0.7788
Epoch 9/500
20100/20100 [==============================] - 3s 139us/sample - loss: 0.5091 -

In [32]:
confusion_matrix(y_true = y_test, y_pred = model.predict_classes(X_test.iloc[:,1:31]))

array([[7252,  458],
       [1366,  824]])

In [33]:
print('accuracy:', accuracy_score(y_true = y_test, y_pred = model.predict_classes(X_test.iloc[:,1:31])),'\n'
      'precision:', precision_score(y_true = y_test, y_pred = model.predict_classes(X_test.iloc[:,1:31])),'\n'
      'recall:',recall_score(y_true = y_test, y_pred = model.predict_classes(X_test.iloc[:,1:31])),'\n'
      'f1:',f1_score(y_test, model.predict_classes(X_test.iloc[:,1:31])))

accuracy: 0.8157575757575758 
precision: 0.6427457098283932 
recall: 0.37625570776255707 
f1: 0.4746543778801843


The results slightly differ. It is probably due to finding better weights for synapses that overall could have better predictions. In other words, when the solver finds the minimum, it does not always come necessarily to a global minimum. It can be somewhere near to that point or stay in the local minumum. That can be a reason why the second method (Keras) might find with better precision the global minimum of the loss function beacuse it can make more cycles during learning, in our case it is equal to 500. Anyway, the results do not differ a lot. 